version: 2
jobs:
  build:
    docker:
      - image: "circleci/node:latest"
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: test
          command: npm run test:single
      - run:
          name: check coverage
          command: npm run check-coverage
      - run:
          name: report coverage
          command: npm run report-coverage
      - run:
          name: release
          command: npm run semantic-release
